### PR TITLE
[auth] Fix crash on window close on Windows

### LINKED ISSUE #7419: Ente Auth crash on exit
### Description

Ente Auth will crash on exit (can be seen through Windows Reliability History) if you exit using the right-click method on the system tray.

But Ente Auth won't crash if you close the app by simply clicking the X button of the window.

### Version

4.4.4

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

### PR DESCRIPTION
**Pull request by tristan-derez**
## Description

closes #7419 and #7154

On Windows, closing the app window caused a crash. Explicitly terminating the process prevents this.

**Note:** This may be related to [flutter_inappwebview#2512](https://github.com/pichillilorenzo/flutter_inappwebview/issues/2512), though the exact cause is unclear.

**Solution:** Call `TerminateProcess()` on the current process handle during app closure on Windows.

## Tests

Tested locally on Windows.

### CODE REVIEW

File: mobile/apps/auth/lib/app/view/app.dart [hunk 1]
```diff
@@ -210,6 +211,11 @@ class _AppState extends State<App>
         windowManager.setSkipTaskbar(false);
         break;
       case 'exit_app':
+        if (Platform.isWindows) {
+          final int hProcess = GetCurrentProcess();
+          TerminateProcess(hProcess, 0);
+        }
+        windowManager.setPreventClose(false);
         windowManager.destroy();
```
Comment (prateekmedia) [inline mobile/apps/auth/lib/app/view/app.dart]: Will these and similar lines in window destroy even run if you've killed the process?

File: mobile/apps/auth/lib/app/view/app.dart [hunk 2]
```diff
@@ -223,6 +229,10 @@ class _AppState extends State<App>
       windowManager.hide();
       windowManager.setSkipTaskbar(true);
     } else {
+      if (Platform.isWindows) {
+        final int hProcess = GetCurrentProcess();
+        TerminateProcess(hProcess, 0);
+      }
       windowManager.setPreventClose(false);
       windowManager.destroy();
```
Comment (prateekmedia) [inline mobile/apps/auth/lib/app/view/app.dart]: Same as above.

File: mobile/apps/auth/lib/app/view/app.dart (hunk 1 above)
Comment (tristan-derez) [reply mobile/apps/auth/lib/app/view/app.dart]: Nope, they wont run at all, but thats the point

Comment (prateekmedia) [reply mobile/apps/auth/lib/app/view/app.dart]: So are they even needed then?

Comment (prateekmedia) [reply mobile/apps/auth/lib/app/view/app.dart]: When Platform.isWindows

Comment (tristan-derez) [reply mobile/apps/auth/lib/app/view/app.dart]: You mean that you would like a else statement?

Comment (tristan-derez) [reply mobile/apps/auth/lib/app/view/app.dart]: Because apart if im wrong the process would only be killed on windows. windowManager would be prefered for other OS imo

Comment (prateekmedia) [reply mobile/apps/auth/lib/app/view/app.dart]: Yes like an else. So on windows it would always kill and on other's it would do normal.

Comment (tristan-derez) [reply mobile/apps/auth/lib/app/view/app.dart]: well its already doing that right now but i can add the else for clarity

Comment (prateekmedia) [reply mobile/apps/auth/lib/app/view/app.dart]: Cool, I'm fine with current approach as well.

Comment (prateekmedia) [reply mobile/apps/auth/lib/app/view/app.dart]: Thanks for resolving!
